version: "3"
services:
  gin-example-mysql:
    container_name: gin-example-mysql
    image: mysql:8.0
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: example
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      TZ: 'Asia/Tokyo'
    volumes:
      - gin-example-mysql-data:/var/lib/mysql
volumes:
  gin-example-mysql-data:
